### ISSUE TITLE
Allow disabling the "Are you sure?" prompt

### ISSUE THREAD

**Issue by geajack** [adriantombu/amazon-alternatives#62]
The "Are you sure?" prompt that shows up when you decide to buy on Amazon has led me to uninstall this add-on. From my perspective the trouble is that the add-on just doesn't work well enough and consistently enough to justify that popup - most of the time I use this add-on, I can't find the product I'm looking at on Amazon on any of the linked sites. If it worked more consistently, the popup could be justified, and if there was no popup, the inconsistency wouldn't be a problem - but taken together, they make the add-on a net negative on my browsing experience.

**Comment by adriantombu** [comment]
Hey @geajack, thanks for your concern about this "Are you sure?" ! You're absolutely right about the annoing side of it, there's no point in showing it all the time, even less when you cannot have any alternative, so I just removed it (it was mostly a feature I was testing). It should be available soon in the stores under the 1.6.0 version.

Just for the sake of improving the extension, could you give me a few exemples of pages where you cannot find any alternatives ? That would help me a lot, I know it is far from working perfectly currently and I would really love to remove as much painpoints as possible for the user. Thanks in advance !

**Comment by geajack** [comment]
[Here's](https://www.amazon.fr/s?k=palmer%27s&__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&ref=nb_sb_noss_1) the most recent example I found (and the only one I can think of)
